# Generated by Django 2.2.6 on 2019-11-04 19:32

import audience.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_number_of_places', models.IntegerField()),
                ('audience_size_of_scene', models.CharField(max_length=200, verbose_name='Size of the scene')),
                ('audience_status', django_enumfield.db.fields.EnumField(default=2, enum=audience.models.AudienceStatus)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='username')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
            ],
        ),
    ]
