# Generated by Django 2.2.6 on 2019-11-05 11:29

import audience.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('order_complete', models.BooleanField()),
                ('order_status', django_enumfield.db.fields.EnumField(default=1, enum=audience.models.OrderStatus)),
                ('audience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audience.Audience')),
            ],
        ),
    ]
