# Generated by Django 2.2.6 on 2019-11-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0003_auto_20191105_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='audience_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audience.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.CharField(max_length=200, verbose_name='Your address'),
        ),
    ]
