# Generated by Django 2.2.6 on 2019-11-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0004_auto_20191109_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='audience_user',
        ),
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audience.User'),
        ),
    ]
