# Generated by Django 2.2.6 on 2019-11-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0005_auto_20191110_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='audience_ordered_beforehand',
            field=models.BooleanField(default=False),
        ),
    ]
