# Generated by Django 2.2.6 on 2019-11-12 17:14

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0006_audience_audience_ordered_beforehand'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date_end',
            field=models.DateTimeField(default=datetime.now, blank=True),
        ),
    ]
