# Generated by Django 2.2.6 on 2019-11-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0012_auto_20191112_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date_end',
            field=models.DateTimeField(),
        ),
    ]
